"""
    You will only be writing code in this file and this is the only file submitted to the autograder.
"""
import sys
import csv


def get_version():
    """
        print the version of python that you are using.
    """
    "*** WRITE YOUR CODE HERE ***"
    info = sys.version_info  # return tuple(major, minor, micro, releaselevel, and serial.)
    return f'{info.major}.{info.minor}.{info.micro}'


def alternative_sum(start, n):
    """
        modify the function to return a list with generated by an alternative sum sequence explained
        in the assignment handout
    """
    "*** WRITE YOUR CODE HERE ***"
    # check for valid arguments
    if start <= 0 or n < 5 or n > 20:
        return list()

    # initialize result list with the first 3 elements
    result = [start * (2 ** i) for i in range(0, 3)]

    # add element until reaching n elements
    while len(result) < n:
        result.append(result[-1] + result[-3])

    return result


def order_scores():
    """
        read the files scores.csv in the data directory and return the list of names sorted in
        ascending order of the scores.
    """
    "*** WRITE YOUR CODE HERE ***"
    file = open('data/scores.csv', newline='')  # open .csv file

    reader = csv.DictReader(file)  # create dictionary reader from file

    students = [dict(row) for row in reader]  # create list of students, each student is a dict

    return list(
            map(lambda e: e['name'],
                sorted(students, key=lambda s: s['scores'])  # sort students by ascending scores
                )  # get first names from students
    )  # convert to list
